<?php

namespace ContainerQIP7xFT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_INdY7SxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iNdY7Sx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iNdY7Sx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'voitureRepository' => ['privates', 'App\\Repository\\VoitureRepository', 'getVoitureRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ReservationRepository',
            'voitureRepository' => 'App\\Repository\\VoitureRepository',
        ]);
    }
}
