<?php

namespace Container030JS9D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KvXmggfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.KvXmggf' shared service.
     *
     * @return \App\Controller\FlashBagInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ReservationController::deleteStatique()": the $flashBag argument is type-hinted with the non-existent class or interface: "App\\Controller\\FlashBagInterface". Did you forget to add a use statement?');
    }
}
