<?php

namespace Container030JS9D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UkVCKhRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ukVCKhR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ukVCKhR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'flashBag' => ['privates', '.errored.KvXmggf', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::deleteStatique()": the $flashBag argument is type-hinted with the non-existent class or interface: "App\\Controller\\FlashBagInterface". Did you forget to add a use statement?'],
            'repo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'doctrine' => '?',
            'flashBag' => '?',
            'repo' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
