<?php

namespace Container030JS9D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoiture3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o3cVXXS.App\Entity\Voiture' shared service.
     *
     * @return \App\Entity\Voiture
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.o3cVXXS": it references class "App\\Entity\\Voiture" but no such service exists.');
    }
}
