<?php

namespace Container6sLUICg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YQrdSwfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YQrdSwf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YQrdSwf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'locateurvoiture' => ['privates', '.errored.j90um_y', NULL, 'Cannot determine controller argument for "App\\Controller\\VoitureController::show2()": the $locateurvoiture argument is type-hinted with the non-existent class or interface: "App\\Controller\\LocateurVoiture". Did you forget to add a use statement?'],
        ], [
            'locateurvoiture' => '?',
        ]);
    }
}
