<?php

namespace Container6sLUICg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_J90umYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.j90um_y' shared service.
     *
     * @return \App\Controller\LocateurVoiture
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\VoitureController::show2()": the $locateurvoiture argument is type-hinted with the non-existent class or interface: "App\\Controller\\LocateurVoiture". Did you forget to add a use statement?');
    }
}
