<?php

namespace ContainerS1eEtQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KHoyyPYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.kHoyyPY' shared service.
     *
     * @return \App\Controller\ManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ReservationController::deleteStatique()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?');
    }
}
