<?php

namespace ContainerS1eEtQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Yd6BvXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Yd6BvX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Yd6BvX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.kHoyyPY', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::deleteStatique()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
            'repo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'doctrine' => '?',
            'repo' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
