<?php

namespace ContainerS1eEtQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AN1ZH_FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AN1ZH.f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AN1ZH.f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ReservationController::Affiche' => ['privates', '.service_locator.vJKoCwu', 'get_ServiceLocator_VJKoCwuService', true],
            'App\\Controller\\ReservationController::deleteStatique' => ['privates', '.service_locator.0Yd6BvX', 'get_ServiceLocator_0Yd6BvXService', true],
            'App\\Controller\\VoitureController::Affiche' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController::Affichenonreserve' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController::Affichereserve' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController::addVoiture' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\VoitureController::deleteStatique' => ['privates', '.service_locator.z6uZLW2', 'get_ServiceLocator_Z6uZLW2Service', true],
            'App\\Controller\\VoitureController::updateVoiture' => ['privates', '.service_locator.bVC5iuU', 'get_ServiceLocator_BVC5iuUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ReservationController:Affiche' => ['privates', '.service_locator.vJKoCwu', 'get_ServiceLocator_VJKoCwuService', true],
            'App\\Controller\\ReservationController:deleteStatique' => ['privates', '.service_locator.0Yd6BvX', 'get_ServiceLocator_0Yd6BvXService', true],
            'App\\Controller\\VoitureController:Affiche' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController:Affichenonreserve' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController:Affichereserve' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController:addVoiture' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\VoitureController:deleteStatique' => ['privates', '.service_locator.z6uZLW2', 'get_ServiceLocator_Z6uZLW2Service', true],
            'App\\Controller\\VoitureController:updateVoiture' => ['privates', '.service_locator.bVC5iuU', 'get_ServiceLocator_BVC5iuUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ReservationController::Affiche' => '?',
            'App\\Controller\\ReservationController::deleteStatique' => '?',
            'App\\Controller\\VoitureController::Affiche' => '?',
            'App\\Controller\\VoitureController::Affichenonreserve' => '?',
            'App\\Controller\\VoitureController::Affichereserve' => '?',
            'App\\Controller\\VoitureController::addVoiture' => '?',
            'App\\Controller\\VoitureController::deleteStatique' => '?',
            'App\\Controller\\VoitureController::updateVoiture' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReservationController:Affiche' => '?',
            'App\\Controller\\ReservationController:deleteStatique' => '?',
            'App\\Controller\\VoitureController:Affiche' => '?',
            'App\\Controller\\VoitureController:Affichenonreserve' => '?',
            'App\\Controller\\VoitureController:Affichereserve' => '?',
            'App\\Controller\\VoitureController:addVoiture' => '?',
            'App\\Controller\\VoitureController:deleteStatique' => '?',
            'App\\Controller\\VoitureController:updateVoiture' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
