<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voiture extends \App\Entity\Voiture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'marque', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'puissance', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'prixJours', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'energie', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'idLocateur', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'reservations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'matricule', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'marque', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'puissance', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'prixJours', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'energie', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'idLocateur', '' . "\0" . 'App\\Entity\\Voiture' . "\0" . 'reservations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Voiture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(string $matricule): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(string $marque): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getPuissance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuissance', []);

        return parent::getPuissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setPuissance(string $puissance): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPuissance', [$puissance]);

        return parent::setPuissance($puissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixJours(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixJours', []);

        return parent::getPrixJours();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixJours(string $prixJours): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixJours', [$prixJours]);

        return parent::setPrixJours($prixJours);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture(string $picture): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnergie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnergie', []);

        return parent::getEnergie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnergie(string $energie): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnergie', [$energie]);

        return parent::setEnergie($energie);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLocateur(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLocateur', []);

        return parent::getIdLocateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLocateur(int $idLocateur): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLocateur', [$idLocateur]);

        return parent::setIdLocateur($idLocateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\App\Entity\Reservation $reservation): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', [$reservation]);

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\App\Entity\Reservation $reservation): \App\Entity\Voiture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', [$reservation]);

        return parent::removeReservation($reservation);
    }

}
