<?php

namespace ContainerJFGxsFr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WUTnKhXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wUTnKhX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wUTnKhX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'repository' => 'App\\Repository\\ReservationRepository',
            'router' => '?',
        ]);
    }
}
