<?php

namespace Container8irZqg1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GzdkgTjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GzdkgTj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GzdkgTj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\VoitureRepository', 'getVoitureRepositoryService', true],
            'voiture' => ['privates', '.errored..service_locator.GzdkgTj.App\\Entity\\Voiture', NULL, 'Cannot autowire service ".service_locator.GzdkgTj": it references class "App\\Entity\\Voiture" but no such service exists.'],
        ], [
            'repository' => 'App\\Repository\\VoitureRepository',
            'voiture' => 'App\\Entity\\Voiture',
        ]);
    }
}
