index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        path: /qrcode
        permanent: true

qrcode:
    path: /qrcode
    controller: App\Controller\DefaultController::index
