#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_reservation_update:
  path: /reservations/{id}/edit
  controller: App\Controller\ReservationController::update
  methods: [GET, POST]
  requirements:
    id: '\d+'