#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_role_login:
    path: /role_log
    controller: App\Controller\RoleLoginController::rolelogin



index:
    path: /roue
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        path: /qrcode
        permanent: true

qrcode:
    path: /qrcode
    controller: App\Controller\DefaultController::index
