<?php

namespace ContainerCJ7bSyt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZeniUmZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zeniUmZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zeniUmZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ReservationController::Affiche' => ['privates', '.service_locator.Zl91E0Y', 'get_ServiceLocator_Zl91E0YService', true],
            'App\\Controller\\ReservationController::Affichefront' => ['privates', '.service_locator.vJKoCwu', 'get_ServiceLocator_VJKoCwuService', true],
            'App\\Controller\\ReservationController::addReservation' => ['privates', '.service_locator.oY4vFbW', 'get_ServiceLocator_OY4vFbWService', true],
            'App\\Controller\\ReservationController::deleteStatique' => ['privates', '.service_locator.TiNt8je', 'get_ServiceLocator_TiNt8jeService', true],
            'App\\Controller\\ReservationController::deleteStatique2' => ['privates', '.service_locator.TiNt8je', 'get_ServiceLocator_TiNt8jeService', true],
            'App\\Controller\\ReservationController::modifC' => ['privates', '.service_locator.KMgm63B', 'get_ServiceLocator_KMgm63BService', true],
            'App\\Controller\\ReservationController::modifC2' => ['privates', '.service_locator.KMgm63B', 'get_ServiceLocator_KMgm63BService', true],
            'App\\Controller\\VoitureController::Affiche' => ['privates', '.service_locator..V1sY5x', 'get_ServiceLocator__V1sY5xService', true],
            'App\\Controller\\VoitureController::AfficherClient' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController::Affichernoneserve' => ['privates', '.service_locator..V1sY5x', 'get_ServiceLocator__V1sY5xService', true],
            'App\\Controller\\VoitureController::addVoiture' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\VoitureController::deleteStatique' => ['privates', '.service_locator.z6uZLW2', 'get_ServiceLocator_Z6uZLW2Service', true],
            'App\\Controller\\VoitureController::deleteStatique2' => ['privates', '.service_locator.z6uZLW2', 'get_ServiceLocator_Z6uZLW2Service', true],
            'App\\Controller\\VoitureController::show' => ['privates', '.service_locator.GzdkgTj', 'get_ServiceLocator_GzdkgTjService', true],
            'App\\Controller\\VoitureController::show2' => ['privates', '.service_locator.o3cVXXS', 'get_ServiceLocator_O3cVXXSService', true],
            'App\\Controller\\VoitureController::show3' => ['privates', '.service_locator.o3cVXXS', 'get_ServiceLocator_O3cVXXSService', true],
            'App\\Controller\\VoitureController::updateVoiture' => ['privates', '.service_locator.bVC5iuU', 'get_ServiceLocator_BVC5iuUService', true],
            'App\\Controller\\VoitureController::updateVoiture2' => ['privates', '.service_locator.bVC5iuU', 'get_ServiceLocator_BVC5iuUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ReservationController:Affiche' => ['privates', '.service_locator.Zl91E0Y', 'get_ServiceLocator_Zl91E0YService', true],
            'App\\Controller\\ReservationController:Affichefront' => ['privates', '.service_locator.vJKoCwu', 'get_ServiceLocator_VJKoCwuService', true],
            'App\\Controller\\ReservationController:addReservation' => ['privates', '.service_locator.oY4vFbW', 'get_ServiceLocator_OY4vFbWService', true],
            'App\\Controller\\ReservationController:deleteStatique' => ['privates', '.service_locator.TiNt8je', 'get_ServiceLocator_TiNt8jeService', true],
            'App\\Controller\\ReservationController:deleteStatique2' => ['privates', '.service_locator.TiNt8je', 'get_ServiceLocator_TiNt8jeService', true],
            'App\\Controller\\ReservationController:modifC' => ['privates', '.service_locator.KMgm63B', 'get_ServiceLocator_KMgm63BService', true],
            'App\\Controller\\ReservationController:modifC2' => ['privates', '.service_locator.KMgm63B', 'get_ServiceLocator_KMgm63BService', true],
            'App\\Controller\\VoitureController:Affiche' => ['privates', '.service_locator..V1sY5x', 'get_ServiceLocator__V1sY5xService', true],
            'App\\Controller\\VoitureController:AfficherClient' => ['privates', '.service_locator.U0A_QMQ', 'get_ServiceLocator_U0AQMQService', true],
            'App\\Controller\\VoitureController:Affichernoneserve' => ['privates', '.service_locator..V1sY5x', 'get_ServiceLocator__V1sY5xService', true],
            'App\\Controller\\VoitureController:addVoiture' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\VoitureController:deleteStatique' => ['privates', '.service_locator.z6uZLW2', 'get_ServiceLocator_Z6uZLW2Service', true],
            'App\\Controller\\VoitureController:deleteStatique2' => ['privates', '.service_locator.z6uZLW2', 'get_ServiceLocator_Z6uZLW2Service', true],
            'App\\Controller\\VoitureController:show' => ['privates', '.service_locator.GzdkgTj', 'get_ServiceLocator_GzdkgTjService', true],
            'App\\Controller\\VoitureController:show2' => ['privates', '.service_locator.o3cVXXS', 'get_ServiceLocator_O3cVXXSService', true],
            'App\\Controller\\VoitureController:show3' => ['privates', '.service_locator.o3cVXXS', 'get_ServiceLocator_O3cVXXSService', true],
            'App\\Controller\\VoitureController:updateVoiture' => ['privates', '.service_locator.bVC5iuU', 'get_ServiceLocator_BVC5iuUService', true],
            'App\\Controller\\VoitureController:updateVoiture2' => ['privates', '.service_locator.bVC5iuU', 'get_ServiceLocator_BVC5iuUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ReservationController::Affiche' => '?',
            'App\\Controller\\ReservationController::Affichefront' => '?',
            'App\\Controller\\ReservationController::addReservation' => '?',
            'App\\Controller\\ReservationController::deleteStatique' => '?',
            'App\\Controller\\ReservationController::deleteStatique2' => '?',
            'App\\Controller\\ReservationController::modifC' => '?',
            'App\\Controller\\ReservationController::modifC2' => '?',
            'App\\Controller\\VoitureController::Affiche' => '?',
            'App\\Controller\\VoitureController::AfficherClient' => '?',
            'App\\Controller\\VoitureController::Affichernoneserve' => '?',
            'App\\Controller\\VoitureController::addVoiture' => '?',
            'App\\Controller\\VoitureController::deleteStatique' => '?',
            'App\\Controller\\VoitureController::deleteStatique2' => '?',
            'App\\Controller\\VoitureController::show' => '?',
            'App\\Controller\\VoitureController::show2' => '?',
            'App\\Controller\\VoitureController::show3' => '?',
            'App\\Controller\\VoitureController::updateVoiture' => '?',
            'App\\Controller\\VoitureController::updateVoiture2' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ReservationController:Affiche' => '?',
            'App\\Controller\\ReservationController:Affichefront' => '?',
            'App\\Controller\\ReservationController:addReservation' => '?',
            'App\\Controller\\ReservationController:deleteStatique' => '?',
            'App\\Controller\\ReservationController:deleteStatique2' => '?',
            'App\\Controller\\ReservationController:modifC' => '?',
            'App\\Controller\\ReservationController:modifC2' => '?',
            'App\\Controller\\VoitureController:Affiche' => '?',
            'App\\Controller\\VoitureController:AfficherClient' => '?',
            'App\\Controller\\VoitureController:Affichernoneserve' => '?',
            'App\\Controller\\VoitureController:addVoiture' => '?',
            'App\\Controller\\VoitureController:deleteStatique' => '?',
            'App\\Controller\\VoitureController:deleteStatique2' => '?',
            'App\\Controller\\VoitureController:show' => '?',
            'App\\Controller\\VoitureController:show2' => '?',
            'App\\Controller\\VoitureController:show3' => '?',
            'App\\Controller\\VoitureController:updateVoiture' => '?',
            'App\\Controller\\VoitureController:updateVoiture2' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
