<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVOAQ7wb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVOAQ7wb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVOAQ7wb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVOAQ7wb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVOAQ7wb\App_KernelDevDebugContainer([
    'container.build_hash' => 'VOAQ7wb',
    'container.build_id' => '8b523cb8',
    'container.build_time' => 1680974130,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVOAQ7wb');
