<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLDHSU86\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLDHSU86/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLDHSU86.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLDHSU86\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLDHSU86\App_KernelDevDebugContainer([
    'container.build_hash' => 'LDHSU86',
    'container.build_id' => 'bbcfefe6',
    'container.build_time' => 1680092662,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLDHSU86');
