<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_reservation' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/reservation']], [], [], []],
    'app_reservation_add' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::addReservation'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/reservation/Add']], [], [], []],
    'app_DeleteReservation' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::deleteStatique'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/deleteReservation']], [], [], []],
    'app_reservationaffichefront' => [[], ['_controller' => 'App\\Controller\\ReservationController::Affichefront'], [], [['text', '/reservation/client/Affichelist']], [], [], []],
    'exportexcel' => [[], ['_controller' => 'App\\Controller\\ReservationController::exportacademieToExcelAction'], [], [['text', '/exportexcel']], [], [], []],
    'app_DeleteReservation2' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::deleteStatique2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/client/deleteReservation']], [], [], []],
    'app_reservationaffiche' => [[], ['_controller' => 'App\\Controller\\ReservationController::Affiche'], [], [['text', '/reservation/Affichelist']], [], [], []],
    'modifC' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::modifC'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifC']], [], [], []],
    'modifC2' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::modifC2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifC/back']], [], [], []],
    'exportpdf' => [[], ['_controller' => 'App\\Controller\\ReservationController::exportToPdf'], [], [['text', '/exportpdf']], [], [], []],
    'app_voiture' => [[], ['_controller' => 'App\\Controller\\VoitureController::index'], [], [['text', '/voiture']], [], [], []],
    'app_voitureaffiche' => [[], ['_controller' => 'App\\Controller\\VoitureController::Affiche'], [], [['text', '/voiture/Affichelist']], [], [], []],
    'app_voitureaffichenonreserve' => [[], ['_controller' => 'App\\Controller\\VoitureController::Affichernoneserve'], [], [['text', '/voiture/Affichelocateur']], [], [], []],
    'app_DeleteVoiture' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::deleteStatique'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/deleteVoiture']], [], [], []],
    'app_DeleteVoiture2' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::deleteStatique2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/locateurvoiture/deleteVoiture']], [], [], []],
    'updateVoiture' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::updateVoiture'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateVoiture']], [], [], []],
    'updateVoiture2' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::updateVoiture2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateVoiture//locateurvoiture']], [], [], []],
    'addVoiture' => [[], ['_controller' => 'App\\Controller\\VoitureController::addVoiture'], [], [['text', '/voiture/add']], [], [], []],
    'app_voiture_show' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/show']], [], [], []],
    'app_locateurvoiture_show' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::show2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/locateurvoiture/show']], [], [], []],
    'app_voitureaffichClient' => [[], ['_controller' => 'App\\Controller\\VoitureController::AfficherClient'], [], [['text', '/voiture/AffichelistClient']], [], [], []],
    'app_Clientvoiture_show' => [['id'], ['_controller' => 'App\\Controller\\VoitureController::show3'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/voiture/Clientvoiture/show']], [], [], []],
    'recherche' => [[], ['_controller' => 'App\\Controller\\VoitureController::Recherche'], [], [['text', '/voiture/recherche']], [], [], []],
    'qr_code_generate' => [['builder', 'data'], ['_controller' => 'Endroid\\QrCodeBundle\\Controller\\GenerateController'], ['data' => '[\\w\\W]+'], [['variable', '/', '[\\w\\W]+', 'data', true], ['variable', '/', '[^/]++', 'builder', true], ['text', '/qr-code']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_reservation_update' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::update'], ['id' => '\\d+'], [['text', '/edit'], ['variable', '/', '\\d+', 'id', true], ['text', '/reservations']], [], [], []],
];
